# Generated by Django 4.2.16 on 2024-09-17 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=10, unique=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('number_of_beds', models.PositiveIntegerField()),
                ('room_capacity', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='rooms/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.property')),
            ],
        ),
    ]
