# Generated by Django 4.2.16 on 2024-09-26 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_roomamenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, help_text='Comma separated amenities, e.g., Wi-Fi, Parking, Pool', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='map_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
