# Generated by Django 4.2.16 on 2024-09-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_roomamenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_amenities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
