# Generated by Django 4.2.16 on 2024-09-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_room_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, help_text='Comma separated amenities, e.g., Wi-Fi, Parking, Pool', max_length=255),
        ),
    ]
