# Generated by Django 4.2.16 on 2024-09-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_alter_room_map_url_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='should_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
