# Generated by Django 4.2.16 on 2024-10-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_booking_should_pay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total',
            new_name='per_night',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='should_pay',
            new_name='total_amount',
        ),
    ]
