# Generated by Django 4.2.16 on 2024-10-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_rename_total_booking_per_night_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
