# Generated by Django 4.2.16 on 2024-10-09 05:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='canceletion_policy',
            field=models.CharField(choices=[('Non Refundable', 'Non Refundable'), ('Flexible', 'Flexible'), ('Moderate', 'Moderate')], default='Flexible', max_length=250),
        ),
        migrations.AddField(
            model_name='room',
            name='check_in',
            field=models.TimeField(default=datetime.datetime(2024, 10, 9, 5, 23, 41, 385493, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='check_out',
            field=models.TimeField(default=datetime.datetime(2024, 10, 9, 5, 23, 48, 994940, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_pet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_unmarried',
            field=models.BooleanField(default=False),
        ),
    ]
