# Generated by Django 4.2.16 on 2024-10-09 06:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_room_canceletion_policy_room_check_in_room_check_out_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='check_in',
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AlterField(
            model_name='room',
            name='check_out',
            field=models.TimeField(default=datetime.time(11, 0)),
        ),
    ]
