# Generated by Django 4.2.16 on 2024-10-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_alter_room_check_in_alter_room_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
