# Generated by Django 4.2.16 on 2024-10-09 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_property_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_amenities',
            field=models.TextField(default=datetime.datetime(2024, 10, 9, 9, 4, 47, 651845, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
