# Generated by Django 4.2.16 on 2024-10-16 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_room_room_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_amenities',
        ),
    ]
