# Generated by Django 4.2.16 on 2024-10-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Room', 'Room'), ('Hotel', 'Hotel'), ('Resort', 'Resort'), ('Office Space', 'Office Space'), ('Hotel Apartment', 'Hotel Apartment'), ('Apartment', 'Apartment'), ('Paying Guest (PG)', 'Paying Guest (PG)'), ('Store', 'Store')], default='Room', max_length=50),
        ),
    ]
