# Generated by Django 4.2.16 on 2024-10-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_property_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_office_space',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='price_per_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='square_footage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
