# Generated by Django 4.2.16 on 2024-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_property_is_office_space_property_lease_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_office_space',
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('room', 'Room'), ('hotel', 'Hotel'), ('resort', 'Resort'), ('office', 'Office Space'), ('apartment', 'Apartment'), ('hotel_apartment', 'Hotel Apartment'), ('pg', 'Paying Guest'), ('store', 'Store')], default='room', max_length=50),
        ),
    ]
