# Generated by Django 4.2.16 on 2024-10-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_remove_property_is_office_space_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='lease_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='price_per_sqft',
        ),
        migrations.RemoveField(
            model_name='property',
            name='square_footage',
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('room', 'Room'), ('hotel', 'Hotel'), ('resort', 'Resort'), ('office', 'Office Space'), ('apartment', 'Apartment'), ('hotel_apartment', 'Hotel Apartment'), ('pg', 'Paying Guest'), ('store', 'Store')], default='Room', max_length=50),
        ),
    ]
